<?php
// $Id: feedmine.module,v 1.1.4.1 2009/05/24 19:28:35 dougkress Exp $

/*
* @file
* The Feedmine module provides Drupal Blocks for users to enter comments
* which are inserted directly into the specified Redmine database.
*
* To configure, go to admin/settings/feedmine and set up your Redmine
* database.
*
* For more information on Chiliproject, please go to http://www.chiliproject.org
*
*/
//Feedmine Menu

function feedmine_menu() {
  $items = array();

  $items['admin/settings/feedmine'] = array(
    'title' => 'Feedmine',
    'page arguments' => array('feedmine_settings_form'),
    'access arguments' => array('feedmine settings'),
    'type' => MENU_NORMAL_ITEM,
   );
 
 $items['admin/settings/feedmine/list'] = array(
    'title' => 'Project List',
    'description' => 'Project List',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feedmine_project_list'),
    'access arguments' => array('feedmine project list'),
    'type' => MENU_NORMAL_ITEM,
   );
  return $items;
}

//User Permissions
function feedmine_perm() {
  return array('feedmine settings');
  return array('feedmine project list');
}


function feedmine_get_list($entity, $label = 'name', $where = NULL) {
  // Generic rails-based entity list. Assumes standard rails table construction.
  $db = variable_get('redmine_database', '');
  if (!$db) {
    return array();
  }

  $table = $db .'.'. $entity;

  $sql = "SELECT id, $label label FROM $table";
  if (isset($where) && !empty($where)) {
    $sql .= " WHERE ". $where;
  }
  $sql .= " ORDER BY id";
  $list_ref = db_query($sql);
  $list = array();

  while ($item = db_fetch_object($list_ref)) {
    $list[$item->id] = $item->label;
  }
  return $list;
}

function feedmine_database_list() {
  // $db_list_ref = db_query('SELECT TABLE_SCHEMA Database FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = "issues"');
  // TODO: Abstract this.
  $db_list_ref = db_query('SHOW DATABASES');
  $db_list = array();
  while ($db = db_fetch_object($db_list_ref)) {
    // Only add databases that look like Redmine databases...
    if (db_result(db_query('SHOW TABLES FROM %s LIKE "enumerations"', $db->Database)) &&
        db_result(db_query('SHOW TABLES FROM %s LIKE "issues"', $db->Database))) { $db_list[$db->Database] = $db->Database;
    }
  }
  return $db_list;
}

//Project List page
function feedmine_project_list() {
  
  $header = array('Name', 'Operations');
  $rows = array();
  $sql = 'SELECT module FROM `blocks` WHERE `module` LIKE "feedmine"';
  $res = db_query($sql);
  while ($row = db_fetch_array($res)) {
    $rows[] = $row;
  }
  print theme('table', $header, $rows);
}

//Settings page
function feedmine_settings_form() {
  $form = array();
  $database_list = feedmine_database_list();

  if (!$database_list) {
    $form['message'] = array('#value' => '<h2>There are no Chiliproject databases located in the current database instance. To install Chiliproject, please visit '. 
l('https://www.chiliproject.org', 'chiliproject.org') .' for instructions.');
    return $form;
  }
  $redmine_database = variable_get('redmine_database', '');
  if (!$redmine_database) {
    // If no database was previously set, use the first redmine-looking database
    // available by default.
    variable_set('redmine_database', current($database_list));
  }


  $form['redmine_database'] = array(
    '#type' => 'select',
    '#title' => t('Chiliproject database'),
    '#options' => $database_list,
    '#default_value' => $redmine_database,
  );

  $project_id = variable_get('redmine_project_id', 0);
  $form['redmine_project_id'] = array(
    '#type' => 'select',
    '#title' => t('Project'),
    '#options' => feedmine_get_list('projects'),
    '#default_value' => $project_id,
  );

  $form['redmine_tracker_id'] = array(
      '#type' => 'select',
      '#title' => t('Select Tracker'),
      '#options' => feedmine_get_list('trackers', 'name'),
      '#default_value' => variable_get('redmine_tracker_id', 0),
    ); 


  $form['redmine_priority_id'] = array(
    '#type' => 'select',
    '#title' => t('Priority'),
    '#options' => feedmine_get_list('enumerations', 'name', 'type ="IssuePriority"'),
    '#default_value' => variable_get('redmine_priority_id', 0),
    );

  $user_list = feedmine_get_list('users', "concat(firstname, ' ', lastname, ' (', login, ')')");
 

//  $form['redmine_owner_id'] = array(
//    '#type' => 'select',
//    '#title' => t('Select Ticket owner / creator'),
//    '#options' => $user_list,
//   '#default_value' => variable_get('redmine_owner_id', 0),
//    );

  array_unshift($user_list, 'Unassigned');
  $form['redmine_assigned_to_id'] = array(
    '#type' => 'select',
    '#title' => t('Select Assigned To user'),
    '#options' => $user_list,
    '#default_value' => variable_get('redmine_assigned_to_id', 0),
    );

  $form['redmine_feedback_thankyou'] = array(
    '#type' => 'textarea',
    '#title' => t('Thank you message displayed after submittal'),
    '#default_value' => variable_get('redmine_feedback_thankyou', t('Thank you for your feedback.')),
  );
  return system_settings_form($form);
}



//Creating Blocks for forms
function feedmine_block($op = 'list', $delta = 0, $edit = array()) {
  global $user;
  switch ($op) {
    case 'list':
      $blocks = array();
      if (variable_get('redmine_database', '')) {
        $blocks[0]['info'] = t('Feedmine Page Feedback');
        $blocks[1]['info'] = t('Feedmine Page Feedback (2)'); // For alternate block positions
        $blocks[2]['info'] = t('Feedmine Page Feedback (3)');
        $blocks[3]['info'] = t('Feedmine Page Feedback (4)');
      }
      return $blocks;

    case 'view':
      $block = NULL;
      switch ($delta) {
        case 0:
        case 1:
        case 2:
        case 3:
          $block['title'] = t('Submit a ticket');
          $block['content'] = feedmine_page_block();
          break;
      }
      return $block;
  }
}

function feedmine_page_block() {
  $form = drupal_get_form('feedmine_page_form');
  return theme('feedmine_page', $form);
}

function feedmine_page_form() {

  $form['instructions1'] = array(
    '#value' => theme('feedmine_instructions1'),
  );

  $form['category_id'] = array(
    '#title' => t('Category'),
    '#type' => 'select',
    '#options' => feedmine_get_list('issue_categories', 'name', 'project_id = '. variable_get('redmine_project_id', 1)),
  );
 
 $form['subject'] = array(
    '#type' => 'textarea',
    '#title' => t('Subject*'),
    '#cols' => 100,
    '#rows' => 1,
    '#resizable' => FALSE,
  );

  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Description*'),
    '#cols' => 100,
    '#rows' => 6,
    '#resizable' => FALSE,
  );

  $form['redmine_priority_id'] = array(
    '#type' => 'select',
    '#title' => t('Priority'),
    '#options' => feedmine_get_list('enumerations', 'name', 'type ="IssuePriority"'),
    '#default_value' => variable_get('redmine_priority_id', 0),
    );

 $form['redmine_tracker_id'] = array(
   '#type' => 'radios',
   '#title' => t('Type of ticket'),
   '#options' => feedmine_get_list('trackers', 'name'),
   '#default_value' => variable_get('redmine_tracker_id', 0),
  );  

  $form['instructions2'] = array(
    '#value' => theme('feedmine_instructions2'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  $form['clear'] = array(
    '#name' => 'clear',
    '#type' => 'button',
    '#value' => t('Reset'),
    '#attributes' => array('onclick' => 'this.form.reset(); return false;'),
  );

  return $form;
 }

function feedmine_page_form_validate($form, $form_state) {
  if (!$form_state['values']['subject']) {
    form_set_error('subject', t('Please enter a Subject'));
  }
  if (!$form_state['values']['description']) {
    form_set_error('description', t('Please enter a description'));
  }
}

function feedmine_page_form_submit($form, $form_state) {
  $db = variable_get('redmine_database', '');
  global $user;
  $project_id = variable_get('redmine_project_id', 0);

  if (!$project_id) {
    return;
  }

  $tracker_id = $form_state['values']['redmine_tracker_id'];
  $category_id = $form_state['values']['category_id'];
  $status_id = db_result(db_query("SELECT id FROM $db.issue_statuses WHERE is_closed = 0 AND is_default = 1 ORDER BY position LIMIT 1"));
  $assigned_to_id = variable_get('redmine_assigned_to_id', 0);
  $author_id = variable_get('feedmine_author', $text);
  $priority_id = $form_state['values']['redmine_priority_id'];
  $text = $form_state['values']['description'];
  $subject = $form_state['values']['subject'];
  $root_id = db_result(db_query("SELECT auto_increment FROM information_schema.tables WHERE table_name='issues'"));
  $description = theme('feedmine_ticket_description', $text);

  db_query
    ("INSERT INTO $db.issues (tracker_id, project_id, subject, description, category_id, status_id, assigned_to_id, priority_id, author_id, lock_version, created_on, updated_on, root_id, lft, rgt)
    VALUES (%d, %d, '%s', '%s', %d, %d, %d, %d, %d, 0, current_timestamp, current_timestamp, %d, %d, %d)",
    $tracker_id, $project_id, $subject, $description, $category_id, $status_id, $assigned_to_id, $priority_id, $author_id, $root_id, $lft, $rgt);

  drupal_set_message(variable_get('redmine_feedback_thankyou', t('Thank you. Your ticket has been submitted.')));
  return;
}

//Check if user exists. If it does use the user account as the author id if not create.
  function feedmine_author($form, $form_state) {
        $db = variable_get('redmine_database', '');
        $project_id = variable_get('redmine_project_id', 0);
        global $user;

  db_query
    ("INSERT INTO $db.users (id, login, mail, admin, status, last_login_on, language, auth_source_id, type, identity_url, mail_notification)
    VALUES ('$user->id', '$user->name', '$user->mail', '0', '1', 'NULL', 'en', 'NULL', 'User', 'NULL','all')
    ON DUPLICATE KEY UPDATE id = VALUES(id), login = VALUES(login), mail = VALUES(mail)");

  return;
}

function feedmine_theme() {
  return array(
    'feedmine_ticket_subject' => array(
      'arguments' => array('text' => NULL),
    ),
    'feedmine_ticket_description' => array(
      'arguments' => array('text' => NULL),
    ),
    'feedmine_page' => array(
      'arguments' => array('form' => NULL),
    ),
    'feedmine_instructions1' => array(
      'arguments' => array(),
    ),
    'feedmine_instructions2' => array(
      'arguments' => array(),
    ),
  );
}

function theme_feedmine_ticket_subject($text) {
  return drupal_substr(str_replace("\n", "", $text), 0, 40);
}

function theme_feedmine_ticket_description($text) {
  global $user;
  $url = $_SERVER['HTTP_REFERER'];
  $user_agent = $_SERVER['HTTP_USER_AGENT'];
  $host = $_SERVER['HTTP_HOST'];
  $description = <<<TEXT
*Firstname:* $user->firstname
*Lastname:* $user->lastname
$text

*Email:* $user->mail
*User computer/device:* $user_agent
*User Project ID:* $user->uid ($host/user/$user->uid)
*Username:* $user->name
*URL Sent From:* $url

TEXT;
  return $description;
}

function theme_feedmine_page($form) {
  $output = <<<OUTPUT
  <div class="feedback">
    $form
  </div>
OUTPUT;
  return $output;
}

function theme_feedmine_instructions1() {
  return '<div class="feedback-status">* = <i>Required</i></div>';
}

function theme_feedmine_instructions2() {
  return '';
}
